import dotenv from "dotenv";
import {Secret} from "jsonwebtoken";
dotenv.config({ override: true });
export const ACCESS_TOKEN_SECRET = process.env.SECRET_KEY as Secret;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET as string;
export const MYSQL_HOST = process.env.DBHOST as string;
export const MYSQL_USER = process.env.DBUSER as string;
export const MYSQL_PASSWORD = process.env.DBPASSWORD as string;
export const MYSQL_DATABASE = process.env.DATABASE as string;
export const REFRESH_TOKEN_EXPIRES = process.env.REFRESH_TOKEN_EXPIRES_IN as string;
export const TOKEN_EXPIRES_IN = process.env.TOKEN_EXPIRES_IN as string;
export const NODE_ENV = process.env.NODE_ENV || 'development' as string;
export const DEVELOPMENT_IP = process.env.DEVELOPMENT_IP || 'http://localhost:5173' as string;
export const REDIS_URL = process.env.REDIS_URL as string;
export const LOW_ALERT_THRESHOLD = parseInt(process.env.LOW_ALERT_THRESHOLD as string) || 10;
export const ORDERID_PREFIX = process.env.ORDERID_PREFIX as string || 'ORD-DS';
export const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET_TEST as string;
export const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID_TEST as string;
export const RAZORPAY_WEBHOOK_SECRET = process.env.RAZORPAY_WEBHOOK_SECRET as string;
export const DELIVERY_DISTANCE_THRESHOLD_KM = parseInt(process.env.DELIVERY_DISTANCE_THRESHOLD_KM as string) || 2000;